[project]
name = "agent-development-kit-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deprecated>=1.2.18",
    "google-adk>=1.14.1",
    "litellm>=1.77.1",
    "pytz>=2025.2",
]
